import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import '@testing-library/jest-dom/vitest';
import type {AiDraft} from '@/lib/ai';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {AiTools} from './AiTools';
import {createInitialAppState} from '@/lib/app-state';
const mock=vi.hoisted(()=>({call:vi.fn()}));
vi.mock('@/firebase',()=>({db:null,functions:null}));
vi.mock('@/lib/ai',async importOriginal=>({...await importOriginal<typeof import('@/lib/ai')>(),callService:mock.call}));
const free={plan:'free',canPreview:true,features:{aiVoice:false,aiReview:false}};
const premium={plan:'premium',canPreview:true,features:{aiVoice:true,aiReview:true}};
describe('AI feature preview',()=>{
  afterEach(cleanup);
  beforeEach(()=>mock.call.mockReset());
  it('switches both AI controls together while never submitting payment',async()=>{
    mock.call.mockImplementation(async(name,data)=>name==='setFamilyPreviewPlan'?(data.plan==='premium'?premium:free):free);
    render(<AiTools familyId="test" app={createInitialAppState()} onSave={()=>true}/>);
    fireEvent.click(screen.getByRole('button',{name:'プラン・AI'}));
    const toggle=await screen.findByRole('switch');
    expect(screen.getByRole('button',{name:'AIアドバイスを見る'})).toBeDisabled();
    fireEvent.click(toggle);
    await waitFor(()=>expect(screen.getByRole('switch')).toHaveAttribute('aria-checked','true'));
    fireEvent.click(screen.getByRole('checkbox'));
    expect(screen.getByRole('button',{name:'AIアドバイスを見る'})).toBeEnabled();
    fireEvent.click(screen.getByRole('switch'));
    await waitFor(()=>expect(screen.getByRole('button',{name:'AIアドバイスを見る'})).toBeDisabled());
    expect(mock.call.mock.calls.every(([name])=>['getFamilyAccess','setFamilyPreviewPlan'].includes(name))).toBe(true);
  });
  it('keeps mixed records as drafts and requires resolving the unknown time',async()=>{
    const onSave=vi.fn((_events:AiDraft[])=>true),now=Date.now();
    mock.call.mockImplementation(async name=>name==='twinlyAi'?{events:[{babyId:'A',type:'milk',milkMl:70,timestamp:now,clarification:''},{babyId:'B',type:'milk',milkMl:20,timestamp:now-900000,clarification:''},{babyId:'B',type:'diaper',diaperKind:'pee',timestamp:null,clarification:'その後'}]}:premium);
    render(<AiTools familyId="test" app={createInitialAppState()} onSave={onSave}/>);
    fireEvent.click(screen.getByRole('button',{name:'プラン・AI'}));
    await screen.findByRole('switch');fireEvent.click(screen.getByRole('checkbox'));
    fireEvent.change(screen.getByRole('textbox'),{target:{value:'奏汰70、日向は15分前に20、その後おしっこ'}});
    fireEvent.click(screen.getByRole('button',{name:'AIで解析して確認'}));
    const save=await screen.findByRole('button',{name:'確認した3件を保存'});
    expect(save).toBeDisabled();expect(onSave).not.toHaveBeenCalled();
    const local=new Date(now-new Date(now).getTimezoneOffset()*60000).toISOString().slice(0,16);
    fireEvent.change(screen.getByLabelText('記録3の時刻'),{target:{value:local}});
    fireEvent.click(save);
    await waitFor(()=>expect(onSave).toHaveBeenCalledTimes(1));
    expect(onSave.mock.calls[0][0].map(e=>[e.babyId,e.type,e.milkMl])).toEqual([['A','milk',70],['B','milk',20],['B','diaper',undefined]]);
  });
});
