import { afterEach, it, expect, vi } from 'vitest';
import '@testing-library/jest-dom/vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { ComfortTools } from './ComfortTools';
import { createInitialAppState } from '@/lib/app-state';
import type { FamilyAccess } from '@/lib/ai';
vi.mock('@/lib/sleep-music',async original=>({...await original<typeof import('@/lib/sleep-music')>(),createSleepSound:()=>({})}));
afterEach(()=>{cleanup();vi.unstubAllGlobals();localStorage.clear();});
it('limits free music to 12 seconds and revokes premium playback on downgrade',async()=>{
  const stop=vi.fn(),close=vi.fn(),gain={cancelScheduledValues:vi.fn(),setValueAtTime:vi.fn(),linearRampToValueAtTime:vi.fn(),value:0};
  vi.stubGlobal('AudioContext',class {currentTime=0;destination={};resume=async()=>{};close=close;createGain=()=>({gain,connect:vi.fn()});createBufferSource=()=>({connect:vi.fn(),start:vi.fn(),stop,onended:null});});
  const app=createInitialAppState();
  const free:FamilyAccess={plan:'free',canPreview:true,features:{aiReview:false,aiChat:false,dailySummaryEmail:false,music:false,themes:false}};
  const premium:FamilyAccess={...free,plan:'premium',features:{...free.features,aiReview:true,aiChat:true,dailySummaryEmail:true,music:true,themes:true}};
  const {rerender}=render(<ComfortTools access={free} app={app} familyId="f"/>);
  fireEvent.click(screen.getByRole('button',{name:'おやすみ音楽'}));
  fireEvent.click(screen.getByRole('button',{name:'心音風（12秒試聴）'}));
  await waitFor(()=>expect(stop).toHaveBeenCalled());
  expect(stop.mock.calls[0][0]).toBeGreaterThan(11);
  expect(stop.mock.calls[0][0]).toBeLessThanOrEqual(12);
  rerender(<ComfortTools access={premium} app={app} familyId="f"/>);
  fireEvent.click(screen.getByRole('button',{name:'星のオルゴール'}));
  await waitFor(()=>expect(screen.getByRole('button',{name:'星のオルゴール・再生中'})).toBeInTheDocument());
  rerender(<ComfortTools access={free} app={app} familyId="f"/>);
  await waitFor(()=>expect(screen.getByRole('button',{name:'停止'})).toBeDisabled());
  expect(close).toHaveBeenCalled();
});